name: cmake

on:
  push:
    paths:
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/cmake.yml"


jobs:

  linux:

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    env:
      FC: gfortran-12

    steps:
    - uses: actions/checkout@v4

    - name: install prereqs (linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt -yq update
        sudo apt -yq install --no-install-recommends libopenmpi-dev libcoarrays-dev libcoarrays-openmpi-dev ninja-build

    - name: install prereqs (mac)
      if: runner.os == 'macOS'
      run: brew install opencoarrays ninja

    - run: cmake --workflow --preset debug

    - run: cmake --workflow --preset release
